### ISSUE TITLE
When I view a text in "bilingual mode" and embed a link in my blog, please don't start my readers out in English-only mode

### ISSUE THREAD

**Issue by unforgettableid** [blockspeiser/Sefaria-Project#114]
Sefaria's current behavior:

* I am viewing a (poorly-translated) text in "bilingual mode"
* I copy the current webpage's URL to the clipboard
* I embed a link in my weblog
* A reader clicks the link
* Sefaria shows him the text in English-only mode.

I wonder if you could please implement the following enhancement:

* When the reader first clicks the link, I would like him to see the text in the same mode I was viewing it in. So, in this case, I would like him to see the text in bilingual mode.

(P.S. Thank you very much for all your work on Sefaria! It's an impressive tool.)

**Comment by blockspeiser** [comment]
We've push a changed so that whenever you do something to affect the interface (change the language or layout, filter the sidebar sources, or highlight an individual line) these changes will be automatically reflecting in URL parameters. 

So now if you visit Sefaria and and you copy a link, it will appear the person who clicked the link just as it did to you.

**Comment by unforgettableid** [comment]
Tested the new change.  It works.  Thank you very much for the change.

And, in general, thank you very much for helping to keep Sefaria running.  :)
